# Generated by Django 5.0 on 2024-08-05 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalProcessorParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização')),
                ('total_links_to_process_per_chunck', models.IntegerField(blank=True, default=5, help_text='total_links_to_process_per_chunck', null=True, verbose_name='total_links_to_process_per_chunck')),
                ('last_pypi_file_index_list_downloaded', models.DateTimeField(blank=True, null=True, verbose_name='last_pypi_file_index_list_downloaded')),
                ('last_pypi_file_links_registered', models.BooleanField(default=False, help_text='last_pypi_file_links_registered', verbose_name='last_pypi_file_links_registered')),
                ('last_pypi_file_links_processed', models.BooleanField(default=False, help_text='last_pypi_file_links_processed', verbose_name='last_pypi_file_links_processed')),
                ('total_links_in_file', models.IntegerField(blank=True, default=0, help_text='total_links_in_file', null=True, verbose_name='total_links_in_file')),
                ('total_links_processed', models.IntegerField(blank=True, default=0, help_text='total_links_processed', null=True, verbose_name='total_links_processed')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PyPiFlapyIndexLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização')),
                ('url', models.CharField(help_text='url', max_length=512, verbose_name='url')),
                ('name', models.CharField(blank=True, help_text='name', max_length=512, verbose_name='name')),
            ],
            options={
                'verbose_name': 'FlaPy URL',
                'verbose_name_plural': 'FlaPy URLs',
            },
        ),
        migrations.CreateModel(
            name='PypiSimpleIndexLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização')),
                ('href', models.CharField(help_text='href', max_length=512, verbose_name='href')),
                ('pypi_project_url', models.CharField(blank=True, help_text='pypi_project_url', max_length=512, verbose_name='pypi_project_url')),
                ('processed_message', models.CharField(blank=True, help_text='processed_message', max_length=512, verbose_name='processed_message')),
                ('processed', models.BooleanField(default=False, help_text='processed', verbose_name='processed')),
                ('successful_processed', models.BooleanField(default=False, help_text='successful_processed', verbose_name='successful_processed')),
                ('home_page_found', models.BooleanField(default=False, help_text='home_page_found', verbose_name='home_page_found')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ALIndexLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização')),
                ('url', models.CharField(help_text='url', max_length=512, verbose_name='url')),
                ('can_run_flapy', models.BooleanField(blank=True, default=False, help_text='can_run_flapy', null=True, verbose_name='can_run_flapy')),
                ('processed_by_flapy_message', models.CharField(blank=True, help_text='processed_message', max_length=512, null=True, verbose_name='processed_message')),
                ('short_description', models.CharField(blank=True, help_text='short_description', max_length=512, null=True, verbose_name='short_description')),
                ('processed_by_flapy', models.BooleanField(blank=True, default=False, help_text='processed', null=True, verbose_name='processed')),
                ('processed_by_flapy_400', models.BooleanField(blank=True, default=False, help_text='processed_by_flapy_400', null=True, verbose_name='processed_by_flapy_400')),
                ('flapy_link', models.ForeignKey(blank=True, help_text='flapy_link', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='al_link', to='extractor.pypiflapyindexlinks', verbose_name='flapy_link')),
                ('similar_flapy_link', models.ForeignKey(blank=True, help_text='similar_flapy_link', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='similar_al_link', to='extractor.pypiflapyindexlinks', verbose_name='similar_flapy_link')),
            ],
            options={
                'verbose_name': 'Awsome Python List Record',
                'verbose_name_plural': 'Awsome Python List Records',
            },
        ),
        migrations.CreateModel(
            name='PypiProcessedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='data de atualização')),
                ('homepage_link', models.CharField(blank=True, help_text='homepage_link', max_length=512, null=True, verbose_name='homepage_link')),
                ('github_link', models.CharField(blank=True, help_text='github_link', max_length=512, null=True, verbose_name='github_link')),
                ('simple_index', models.ForeignKey(help_text='simple_index', on_delete=django.db.models.deletion.DO_NOTHING, to='extractor.pypisimpleindexlinks', verbose_name='simple_index')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
